server:
  port: 9090
security:    
  basic:    
    enabled: true    
  user:    
    name: admin
    password: password
eureka:
  instance:
    hostname: localhost
  client:
#eureka.client.registerWithEureka：false和fetchRegistry：false来表明自己是一个eureka server
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://admin:password@${eureka.instance.hostname}:${server.port}/eureka/